### ISSUE TITLE
Errors at Haley Event at 8 hearts

### ISSUE THREAD

**Issue by thakyZ** [ClxS/SMAPI#102]
I get this error when I go to Cindersap Forest and already married and Haley's cut scene opens.
```[09:51:39.507 AM] [ERROR] An error occurred in the overridden update loop: System.NullReferenceException: Object reference not set to an instance of an object.```
```   at StardewModdingAPI.Inheritance.SGame.get_ThumbstickMotionMargin()```
```   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime)```
Here is the full logs: http://pastebin.com/tc9DQYf8

**Comment by ClxS** [comment]
Hi @thakyZ , CJ released a patch here which should address that issue: https://github.com/ClxS/SMAPI/releases/tag/0.40.0

**Comment by thakyZ** [comment]
@ClxS thanks I will try this version.

**Comment by thakyZ** [comment]
Ok It works now... You can close this issue! :smile:
