### ISSUE TITLE
Error Load API Source / Win7 VC 2015 Community

### ISSUE THREAD

**Issue by diegobh** [ClxS/SMAPI#105]
I got 6 errors after tried to compile SMAPI from source. Could you help me, please?

I've already fixed the references for Stardew Valley and xTile that i got errors.

But i still got 6 errors:

1) Program.cs, Line 377: Error CS0103   The name '_modContentPaths' does not exist in the current context   StardewModdingAPI   C:\Users\Diego\Documents\Visual Studio 2015\Projects\SMAPI-0.40.0\StardewModdingAPI\Program.cs

2) Program.cs, Line 380: Error CS0122   'SGame.RegisterModItem(SObject)' is inaccessible due to its protection level    StardewModdingAPI   C:\Users\Diego\Documents\Visual Studio 2015\Projects\SMAPI-0.40.0\StardewModdingAPI\Program.cs

3) Program.cs, Line 412: Error CS0117   'SGame' does not contain a definition for 'ModLocations'    StardewModdingAPI   C:\Users\Diego\Documents\Visual Studio 2015\Projects\SMAPI-0.40.0\StardewModdingAPI\Program.cs

4) Program.cs, Line 412: Error CS0103   The name 'SGameLocation' does not exist in the current context  StardewModdingAPI   C:\Users\Diego\Documents\Visual Studio 2015\Projects\SMAPI-0.40.0\StardewModdingAPI\Program.cs

5) Program.cs, Line 422: Error CS0117   'SGame' does not contain a definition for 'CurrentLocation' StardewModdingAPI   C:\Users\Diego\Documents\Visual Studio 2015\Projects\SMAPI-0.40.0\StardewModdingAPI\Program.cs

6) Program.cs, Line 422: Error CS0117   'SGame' does not contain a definition for 'LoadOrCreateSGameLocationFromName'   StardewModdingAPI   C:\Users\Diego\Documents\Visual Studio 2015\Projects\SMAPI-0.40.0\StardewModdingAPI\Program.cs

Could you help me, please?

Thank you!

**Comment by Pathoschild** [comment]
@diegobh: the code changes for #153 make building SMAPI from source much easier, and should fix all these errors. If you still have trouble, feel free to [come ask us on the SMAPI Discord](https://discordapp.com/invite/0t3fh2xhHVc6Vdyx). :)
