### ISSUE TITLE
Number of item

### ISSUE THREAD

**Issue by kanyn806** [ClxS/SMAPI#107]
Hi, I´m creating a mod but in the console of API when I write "out_items" it only appears like 400 of the 800 item´s number. I dont know how to solve this, please help me :)

**Comment by Pathoschild** [comment]
There's [a new SMAPI guide](http://canimod.com/guides/creating-a-smapi-mod) which might help. If you have any questions, feel free to [come talk on Discord](https://discord.gg/KCJHWhX) or [the modding forums](http://community.playstarbound.com/forums/mods.215/).
