### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Fofo112** [ClxS/SMAPI#108]
The API keeps crashing when i try to start it

**Comment by ClxS** [comment]
What error do you get?

**Comment by Fofo112** [comment]
yes

**Comment by ClxS** [comment]
Could you post them here? :)

**Comment by Fofo112** [comment]
ok

**Comment by Fofo112** [comment]
[20:50:48] Critical error: System.IO.FileNotFoundException: Could not found: C:\Users\Ade\Downloads\Update\Stardew Valley.exe
   vid StardewModdingAPI.Program.ConfigurePaths()
   vid StardewModdingAPI.Program.Main(String[] args)
[20:50:48] The API will now terminate. Press any key to continue...

**Comment by Fofo112** [comment]
thats everything

**Comment by ClxS** [comment]
Have you placed your StardewModdingAPI.exe next to your Stardew Valley.exe

**Comment by Fofo112** [comment]
does it have to be there?

**Comment by ClxS** [comment]
Yeah :) It has to be next to your Stardew Valley.exe, so if you use Steam like C:/ProgramFiles/Steam/steamapps/common/StardewValley

**Comment by Fofo112** [comment]
what do you mean with next to?

**Comment by Fofo112** [comment]
it tells me that there is a missing method

**Comment by ClxS** [comment]
Are you using Stardew 1.07?

**Comment by Fofo112** [comment]
i don't know how to you tell

**Comment by ClxS** [comment]
I think if you check the log again, it'll say near the top. For example, the top two lines in mine are:
[06:59:30.562 PM] SDV Version: 1.07
[06:59:30.562 PM] SMAPI Version: 0.40.0

**Comment by Fofo112** [comment]
i have 1.03

**Comment by ClxS** [comment]
You'll likely need to update to a later version of Stardew, let me know if it doesn't work on the latest version. :)
