### ISSUE TITLE
Mods refuse to work

### ISSUE THREAD

**Issue by jakurka99** [ClxS/SMAPI#109]
I followed the instructions and it wont load any mods in. I have downloaded all the mod's .DLL file, and placed it in the mods folder not even one will load, when the command prompt screen shows up when i launch the game it doesn't even recognize mods being there

**Comment by ClxS** [comment]
Hey there,
Just realised the readme was out of date. SMAPI no longer just uses the DLL but also requires a manifest.json that goes along side the mod. All up to date mods will provide this.

The new way of installing mods is to copy the mod's folder into your mods folder, you'll end up with a structure like this:
- Mods/
- - - Example Mod
- - - - - - manifest.json
- - - - - - exampleMod.dll
