### ISSUE TITLE
SMAPI wont start

### ISSUE THREAD

**Issue by Goldson94** [ClxS/SMAPI#112]
Everytime it launches windows says its not responding and closes the program.

Unhandled Execption: System.IO.FileNotFoundExeption: Could not load file or assembly 'Stardew Valley, Version=1.0.5938.27386, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified at StardewModdingAPI.Program.main(String[] args)

**Comment by ClxS** [comment]
Hi there, looks like your Stardew Valley.exe is not in the same directory.
This video walks through how to install it. https://www.youtube.com/watch?v=FRvrZogk4cU
