### ISSUE TITLE
it doesnt launch please help

### ISSUE THREAD

**Issue by tahhash** [ClxS/SMAPI#113]
this is the problem i know its related to microsoft xna framework, even when i installed it, it still tell me the same thing.
here is the ErrorLog
[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/ClxS/SMAPI/files/247284/MODDED_ProgramLog.Log_LATEST.txt)

**Comment by ClxS** [comment]
You need to use both the latest version of Stardew (1.07) and the latest version of SMAPI. (0.40.0)

**Comment by tahhash** [comment]
i have it
