### ISSUE TITLE
Year 2 Summer 6th Night Crash

### ISSUE THREAD

**Issue by ImmortalMudkip** [ClxS/SMAPI#117]
Whenever I go to bed on the 6th of Summer, Year 2, the game just freezes. It has happened twice and I assume it is SMAPI because I checked the black box of code and what-not that appears when SMAPI Stardew Valley is launched, and there is a bunch of red text (I assume this is BAD! DANGER!)

**Comment by Gormogon** [comment]
@ImmortalMudkip Can you please provide the output from the latest error log located in %appdata%\StardewValley\ErrorLogs.

**Comment by Pathoschild** [comment]
Since there's been no response in several months, I'll close this now. Feel free to reopen with the requested details if it still happens.
