### ISSUE TITLE
Poor Frame Rate (From Forum)

### ISSUE THREAD

**Issue by ClxS** [ClxS/SMAPI#12]
http://community.playstarbound.com/threads/stardew-modding-api-0-37.108375/page-2#post-2806665

I read through all the comments here, and no one else seems to have my problem, so I made an account to post about it. The frame-rate on my farm is game-breakingly slow whenever I run the API (version 0.37.1). I have some cosmetic mods installed (re-textures for my cat & horse and a couple portraits) and everything works fine when I run the Stardew Valley.exe that came with the game. As soon as I try to run the StardewModdedAPI.exe, though, I can't do anything on my farm. Everywhere else is fine (in the farmhouse, farm cave, around town, literally everywhere except the farm...). Is there something in the API that would cause this? I haven't fully cleared the farm yet, so there's still trees, rocks, and grass everywhere... Is that causing the problem? I'm running the Steam version on Windows 8.1 as an administrator with scaling DPI if that helps. (The game won't open on my computer without scaling DPI)

EDIT: Actually I haven't checked the caves will get back to you with that.
EDIT:EDIT: Caves are fine.

**Comment by Jtfinlay** [comment]
Ran some perf testing. The heaviest hitter is definitely _UpdateEventCalls();_ in SGame.cs . It takes nearly 40% of the application's total CPU usage.

I'll investigate and see if I can clean it up.

**Comment by Jtfinlay** [comment]
Found the issue, we're getting a huge hit from the _Extensions::GetHash_ method. Will fix and have a pr out.

**Comment by ClxS** [comment]
Closed until reported again, looks like the probable fix!

**Comment by speeder** [comment]
ClxS The fix worked, but you forgot to make a quick bugfix release of it, players are still using the slow version.

**Comment by ClxS** [comment]
Woops, thanks for pointing that out. Just released and posted it.
