### ISSUE TITLE
Pressing "M" while F2 debug is active skips seasons

### ISSUE THREAD

**Issue by Sythalin** [ClxS/SMAPI#120]
I'm not sure if this is intentional and I couldn't find any documentation on it.  While playing around with configurations on other mods, I accidentally found this and completely ruined my save file (I thought it was skipping days, didn't realize it was seasons until it was too late).

If it's not noted anywhere, please warn about it so that others don't accidentally stumble upon it and screw themselves.  This was my first playthrough, so at least my restart will be better.

**Comment by AdvizeGH** [comment]
This is not the fault of SMAPI. ConcernedApe set the M key to skip forward through seasons for debugging purposes.

**Comment by Pathoschild** [comment]
SMAPI _is_ the one that enables debug mode when you press `F2`, though. Since it's so easy to accidentally skip a season ([see latest example](https://www.reddit.com/r/StardewValley/comments/56ig48/game_skipped_the_rest_of_the_season_possible/)), it'd be nice if that hotkey was optional and disabled by default.

**Comment by Pathoschild** [comment]
I created a [No Debug Mode](http://www.nexusmods.com/stardewvalley/mods/593/) mod which just disables SMAPI's `F2` debug mode. It's [open-source](https://github.com/Pathoschild/Stardew.NoDebugMode) if you want to reuse the (very simple) code.

**Comment by Pathoschild** [comment]
I suggest pulling the `F2` debug mode out of SMAPI into a separate mod. That way players can install it if they actually mean to, but it's not available by default. If there are no objections, I'll do so for the upcoming SMAPI 1.0 release.

**Comment by Pathoschild** [comment]
Confirmed on Discord, so I'll make that change in 1.0. :)

**Comment by Pathoschild** [comment]
I reimplemented and improved it in the [Debug Mode mod](http://www.nexusmods.com/stardewvalley/mods/679). Debug mode is now removed in the upcoming 1.0 release.
