### ISSUE TITLE
Missing Method Exception, Game does not launch

### ISSUE THREAD

**Issue by pilnok** [ClxS/SMAPI#121]
Hello!

I'm unable to launch the game via the StardewModdingAPI.exe.

The black window pops up, and it populates the following text:

Created log instance
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task System.Threading.Tasks.Task.Run(System.Action)'.
at StardewModingAPI.Log.AsyncColour(Object message, ConsoleColor olour)
at STardewModding.API.Log.AsyncY(Object message)
at StardewModdingAPI.Program.Main(straing[]args)﻿

But nothing else happens. Any keyboard interaction with the program crashes it. 
I have uninstalled and reinstalled it several times, following every youtube tutorial (IDED included) to no success.

Please help, I'm going insane :(

**Comment by pilnok** [comment]
Great news, future people with my problem! I've solved it.

I thought Steam required a updated .NET Framework, so I never even considered it was outdated.
It was!
A quick install and reboot, and SMAPI successfully launches my game.

Happy farming, all!

**Comment by ClxS** [comment]
Glad you were able to solve it! :)
