### ISSUE TITLE
Error while starting SMAPI

### ISSUE THREAD

**Issue by Aestrocorp** [ClxS/SMAPI#122]
[http://imgur.com/a/elYAs](url)

I put the file and its assets into my Stardew Valley folder. I see the _steamapi_ text file. I bought it from GOG not Steam; May that be the issue?

I have version 2.2.0.4 of Stardew Valley. I'm guessing that's 0.04 but on the side it says 1.07.

**Comment by Pathoschild** [comment]
Hello @Aestrocorp. SMAPI works fine with the GOG version. If this still happens with the latest version of Stardew Valley and SMAPI, come ask for help in the [Stardew Valley Discord](https://discord.gg/KCJHWhX) or the [discussion thead on the official forums](http://community.playstarbound.com/threads/stardew-modding-api-0-40-1-1.108375/) and we'll help you figure it out. :)
