### ISSUE TITLE
SMAPI documentation

### ISSUE THREAD

**Issue by lisandro52** [ClxS/SMAPI#124]
Hey guys! First of all, thank you for all the awesome job you are doing with this API!

One thing I saw the project lacked, was some kind of documentation: not just how-tos and tutorials, but actual Class References to look at while making mods (or tweaking the API).
Yesterday, I played around with a couple of docs generator (I tried [Sandcaastle Help File Builder](https://github.com/EWSoftware/SHFB) and [docfx](https://github.com/dotnet/docfx)) and finally settled with the latter one, because it had a simple install process (just unzip the Github release), with a simpler usage (running a command on a shell) and it has a nice Visual Studio integration if you want that too.

[This is the result thus far](http://lisandro52.github.io/api/index.html). It's pretty raw, I know, but I haven't tweaked anything from the configurations yet, so that's the default look.

Of course, this means we'll need to update the code with the corresponding summaries everywhere in order to get the generator's full potential.

Let me know what you think about using this or any other tool! Cheers!

**Comment by Pathoschild** [comment]
Thanks for the research! There's now an official guide at [canimod.com](http://canimod.com/) (in particular _[creating a SMAPI mod: available events](http://canimod.com/guides/creating-a-smapi-mod#available-events)_), and we'll begin adding code documentation over the next few releases to enable class references like this.
