### ISSUE TITLE
Easier way to launch through Steam

### ISSUE THREAD

**Issue by White-Tiger** [ClxS/SMAPI#127]
in your readme, you've suggested to use these launch options `"C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\StardewModdingAPI.exe %command%`
but there's an easier way like `StardewModdingAPI %command%`
Somehow if you omit the `.exe`, Steam tries to figure out the right path, starting from the game's folder.
I've figured it out while trying to have it launch with a relative path, even if it meant to launch through cmd. But luckily, it's not even necessary.

Anyway, I suggest to update the readme so people don't have to figure out their game's path and might end up with mistakes like missing quotes or that like. _(btw. the readme is missing quotes or rather the closing quote)_

**Comment by Pathoschild** [comment]
Thanks! Starting with SMAPI 1.0, we'll probably have an install script (#155) that enables Steam support without further user action. That will work by replacing the `StardewValley.exe` itself (with a backup).
