### ISSUE TITLE
Display Issues (From Forum)

### ISSUE THREAD

**Issue by ClxS** [ClxS/SMAPI#13]
http://community.playstarbound.com/threads/stardew-modding-api-0-37.108375/page-2#post-2806611

anyone help me out the game res is all off when i load the game via tool it shows the windowed screen in full screen please help

**Comment by Jtfinlay** [comment]
Can we get the user to provide screenshots?

**Comment by ClxS** [comment]
Yeah this is the image they attached to another post:
http://i.imgur.com/n8g9Dk1.png

**Comment by Jtfinlay** [comment]
Hmm, I only have the Steam version so I'll be unable to repro. Do we have contributors with the Gog version?

**Comment by ClxS** [comment]
Not that I'm aware of. If his problem sticks for a few more updates I'll buy the Gog version to test it out. I imagine more people would've reported it if it was plain incompatible with the Gog version.

**Comment by ClxS** [comment]
User solved it. Turns out it was an issue with his DPI settings
