### ISSUE TITLE
The time stop sign isn't there and irritates gp

### ISSUE THREAD

**Issue by Kee90** [ClxS/SMAPI#132]
As the titel already says it ... the time sign is gone. Normally when you stop time there was always a t on the left corner which made it clear that it stopped. It is now gone and kinda bothers me bc I then can sometimes not be sure if it really stopped and have to wait few seconds to pass to make sure it really stopped... can you please fix it?

Is that even something that got forgotten by mistake or is it wanted?

**Comment by Pathoschild** [comment]
Hi @Kee90. This is a change in Stardew Valley itself, not the SMAPI mod loader.
