### ISSUE TITLE
Won't start with Stardew 1.1

### ISSUE THREAD

**Issue by Emilinrose** [ClxS/SMAPI#137]
I'm having a similar problem to issue #130 . i've confirmed that i have the latest update, and stardew 1.1. i've tried running it by itself, and through Stardew Valley Package Manager.
it won't post the picture so here i've uploaded it to[ tinypic.](http://i67.tinypic.com/besyue.png)

**Comment by AdvizeGH** [comment]
You attempted to load 12 mods and at least 1 of them is causing your problem. You'll need to remove your mods and ensure that you are only using mods compatible with 1.1 of Stardew Valley. Remember to check both your %appdata%\StardewValley\Mods folder as well as your game's Stardew Valley\Mods directory for mods.

**Comment by ColColonCleaner** [comment]
Similar problem, however there are no errors in the console. The game starts and immediately exits:

https://i.gyazo.com/66a25c7ef18bf6a53ffbae6c53af8705.png

**Comment by ClxS** [comment]
Best to ask for help for this sort of thing on the forums, as I dont actively read the issues for this repository any more.
@ColColonCleaner , it's very likely that one of those 3 mods you have installed is out of date.

**Comment by Pathoschild** [comment]
This probably isn't an issue with SMAPI itself, but with one of the mods you're running. Try removing all your mods to see if that works; if so, re-add each mod one by one until it stops working. You can ask for help [in the official modding forums](http://community.playstarbound.com/forums/mods.215/) or the [Stardew Valley Discord](https://discord.gg/KCJHWhX).

If it happens with no mods installed, feel free to reopen this ticket with a copy of your latest log (see [this guide](http://canimod.com/guides/asking-for-help#information-to-include)).
