### ISSUE TITLE
Instantly Crashes when started up

### ISSUE THREAD

**Issue by kalliecat** [ClxS/SMAPI#138]
I installed it correctly, made sure the %appdata% mods folder is the same as my current mods folder, and made sure there were no conflicting mods. There is no red text in the window when I open it, so it loads as normal but instantly crashes. I am using the updated 1.1 Stardew Valley as well

**Comment by Pathoschild** [comment]
@kalliecat Does this still happen with the latest version? If so, please reply with your latest log file (see [this guide](http://canimod.com/guides/asking-for-help#information-to-include)). If not, let us know so we can close this ticket. :)

**Comment by PrincessNorthern** [comment]
Yes, this is still happening. After clicking on the ModdingAPI to load the game, the console pops up, and then instantly crashes. After following your link to try and pull up error logs, there is no error log in the Stardew Valley folder in AppData. The only folder in Stardew Valley is saves. So there are no error logs to be given. The game is un-launchable through the API, but the normal game works perfectly.

**Comment by Pathoschild** [comment]
@PrincessNorthern: could you come talk with us on the [Stardew Valley Discord](https://discord.gg/KCJHWhX)? Just ping `@Pathoschild` when you arrive, and I'll help you look into it. 

Once we figure it out, I'll document the solution here for anyone else having the same problem. :)
