### ISSUE TITLE
StardewModdingAPI.exe missing?

### ISSUE THREAD

**Issue by ItsaJello** [ClxS/SMAPI#139]
https://gyazo.com/1e3f8248e5bc7e46386bbc93930a5aab
Installation instructions say to run StardewModdingAPI.exe, but I don't see one in the folder either before or after extracting. Is this user error or something wrong with the most recent update?

**Comment by Natsulus** [comment]
You downloaded the source code. Download the release from https://github.com/cjsu/SMAPI/releases
