### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by alyssadupont2k18** [ClxS/SMAPI#149]
I keep hitting the P and I keys, since that is what I used with the version I had earlier, which stopped working due to the game being updated. It keeps closing both the game and the modding API. Just wondering if this could be fixed . . .  :(

**Comment by xx3dgxx** [comment]
If you're using CJB's menu mod, you need to download the Ento patch. That should fix P, not sure about I

**Comment by Pathoschild** [comment]
@alyssadupont2k18: the CJB Item Spawner mod has been abandoned, but there's [an unofficial version that's been updated for 1.1+](http://community.playstarbound.com/threads/smapi-entos-home-of-abandoned-mods.125031/). If you have any trouble, you can ask for help in that discussion thread.
