### ISSUE TITLE
CJB Item Spawner mod problems...

### ISSUE THREAD

**Issue by Maymaymaya** [ClxS/SMAPI#150]
When I press "I" my game crashes, is there a way to fix this? or do I have to wait till its updated?

**Comment by maryellencg** [comment]
It's happening to me, too, so frustrating!

**Comment by Pathoschild** [comment]
Hello @Maymaymaya and @maryellencg. That mod has been abandoned, but there's [an unofficial version that's been updated for 1.1+](http://community.playstarbound.com/threads/smapi-entos-home-of-abandoned-mods.125031/). If you have any trouble, you can ask for help in that discussion thread.
