### ISSUE TITLE
[solved]Unhandled exception error

### ISSUE THREAD

**Issue by ultravigo** [ClxS/SMAPI#161]
I just can't run SMAPI.It just crashes instantly whenever i try to run it.
OS :Win8[X32]
![a76lloq](https://cloud.githubusercontent.com/assets/19861461/19955205/36a41fa2-a1a7-11e6-907b-1bb7efd27457.png)

**Comment by ultravigo** [comment]
Lol 3min after posting i tried extracting files in outside content folder and it worked.

**Comment by Pathoschild** [comment]
I'm glad you were able to fix it so quickly. :)

**Comment by ultravigo** [comment]
It took me 3 hours to find it,anyway thanks for the mod :D
