### ISSUE TITLE
No mods work at all

### ISSUE THREAD

**Issue by michaelcurry35** [ClxS/SMAPI#164]
I downloaded the latest version of SMAPI and when I try to play with a mod the game  doesnt work. For ex. the CJB item spawner I hit "i" and it immediately crashes. Other mods that are supposed to already be there like textures or sell price don't even work either. Im on a Windows 10. Up until this new smapi update not even the API worked
[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/ClxS/SMAPI/files/572958/MODDED_ProgramLog.Log_LATEST.txt)

**Comment by Pathoschild** [comment]
Hi @michaelcurry35. The reason for the error isn't immediately clear from the log, so we'll need to look into it with you. Please ask [in this forum thread](http://community.playstarbound.com/threads/stardew-modding-api-0-40-1-1.108375) or [on Discord](https://discord.gg/KCJHWhX), where more people who can help will see your question. :)
