### ISSUE TITLE
Will not run

### ISSUE THREAD

**Issue by erikbrick** [ClxS/SMAPI#169]
When i try to run StardewModdingAPI, it comes up with this error:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Stardew Valley, Version=1.0.6124.26459, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at StardewModdingAPI.Program.Main(String[] args)

**Comment by Pathoschild** [comment]
Hello @erikbrick. How did you install SMAPI?

Make sure that SMAPI is in the game directory, and that you installed the correct version (e.g. Linux/Mac vs Windows).
