### ISSUE TITLE
1.0 still not support Mac's

### ISSUE THREAD

**Issue by z-mojomoji** [ClxS/SMAPI#174]
After I have downloaded the 1.0 SMAPI for moding Stardew Valley, the SMAPI still cannot install. I have tried to manually install it but the file are still .exe not .app (like the game is). Please help this out. Thanks!

**Comment by Pathoschild** [comment]
Hello @z-mojomoji. Did you follow the [install instructions for Mac](http://canimod.com/guides/using-mods#on-linux-or-mac)?

**Comment by z-mojomoji** [comment]
Hey Pathoschild, I have followed the instructions on the page but still unsuccessful for installing and start Stardew Valley.

**Comment by Pathoschild** [comment]
What problem are you having? When you run `mono install.exe`, what happens?

**Comment by z-mojomoji** [comment]
Hey Pathoschild, it said it can't find the stardew valley file, so I manually install it but in the "mono" folder contained only the .exe api file (which cannot run on mac).

**Comment by Pathoschild** [comment]
Make sure you follow the instructions exactly; you should not be running the `.exe` file directly. If you need help, [come talk on Discord](https://discord.gg/KCJHWhX) and we'll help you figure it out. :)
