### ISSUE TITLE
Screen problem

### ISSUE THREAD

**Issue by dvdhaliem** [ClxS/SMAPI#18]
how can I fix this issue? please help
![stardew](https://cloud.githubusercontent.com/assets/17780964/13719027/bb42c89c-e822-11e5-88c6-854cc09536a6.jpg)

**Comment by speeder** [comment]
Can you give more context? While, when this happened? What SMAPI version you are using? What mods? What were you doing with teh game when this happened?

Looking just at this screenshot I have no idea what I am looking at, to be honest, and I wanna help :)

**Comment by vgturtle127** [comment]
@dvdhaliem I have a feeling your graphics drivers are out of date, because that looks like corruption.

**Comment by dvdhaliem** [comment]
@speeder I'm using SMAPI 0.37.2, that happend when a few minutes I play with CJBCheatsmenu mods. But when I turn off that mods and play with SMAPI, my game its still get that problem. When I tried without SMAPI it works well

**Comment by dvdhaliem** [comment]
![image](https://cloud.githubusercontent.com/assets/17780964/13912487/0ff3716c-ef70-11e5-9b49-45ab790b50ee.png)
I'm just updating my SMAPI to 0.38.2, but it still.
there is some invalid mod dll when I launched it? is that metter?

**Comment by ClxS** [comment]
That's caused by CJBs mod. I think uses that dll to handle saving his config file.
The error is fine :) It just means to say it tried to load that dll but found out it's a mod dll.
