### ISSUE TITLE
Add 1,000,000 Gold to the trainer

### ISSUE THREAD

**Issue by vgturtle127** [ClxS/SMAPI#20]
I think this makes sense, this way you don't have to hammer on the 100,000 Gold option until your hand hurts. :wink:

**Comment by speeder** [comment]
SMAPI has no 100.000 gold option, you are confusing it with CJB's mod.

With SMAPI you can edit your gold (using the command line) to whatever you want.

**Comment by vgturtle127** [comment]
@speeder Sorry, I thought I was using the trainer, not the CJB mod. My bad.

Is there documentation as to what you can do on the command-line with SMAPI?

**Comment by speeder** [comment]
Type help in the command line?

**Comment by vgturtle127** [comment]
@speeder Oh, OK. I tried typing in something a few times before, but it crashed. Let me update Stardew and see if that helps.
