### ISSUE TITLE
Item modifiers

### ISSUE THREAD

**Issue by vgturtle127** [ClxS/SMAPI#24]
I think adding the ability to change item settings would be nice.

An example would be make it possible to plant anything at anytime, or add slots to fishing poles.

**Comment by speeder** [comment]
This is extremely hard to do, and a per item thing, each custom item has its own coding (the fishing pole for example), this need to be coded manually for each item, thus why specific mods are needed (Example: I made a mod solely to edit how sprinklers work, it was a couple days of work, just to edit the sprinklers)

**Comment by vgturtle127** [comment]
@speeder The difficulty of plant quality and fishing rods is pretty crazy, I will look into modding the plants first, I suppose.
