### ISSUE TITLE
Add infinite item addons

### ISSUE THREAD

**Issue by vgturtle127** [ClxS/SMAPI#25]
This would make it so item addons wouldn't break. Really would like this, I go through fishing stuff like crazy. :wink:

**Comment by speeder** [comment]
Mods for this already exist...

**Comment by vgturtle127** [comment]
@speeder Do you know where I can get one? I have checked the Nexus and the Starbound forums, but I haven't found that many mods for SMAPI. I haven't tried the Storm API yet, but I don't know how good that is.
