### ISSUE TITLE
Performance optimisations

### ISSUE THREAD

**Issue by ClxS** [ClxS/SMAPI#52]
I'll do a complete performance check at some point too.

**Comment by vgturtle127** [comment]
Would you like me to use Cppcheck to see if there are any other performance issues?

**Comment by ClxS** [comment]
Feel free to :)
I used CppCheck when I first started on SMAPI but haven't used it since. My plan is to use the runtime profiling tools.

**Comment by vgturtle127** [comment]
@ClxS I just found out they removed support for C# and Java a few releases ago. Unfortunately, I wasn't made aware. :disappointed: 

Some continuous integration stuff should help, though.

**Comment by CJBok** [comment]
closed, because Farmhand

**Comment by vgturtle127** [comment]
@CJBok What is Farmhand?

**Comment by ClxS** [comment]
@vgturtle127 , and in-development SMAPI replacement :) https://github.com/ClxS/Stardew-Farmhand

**Comment by vgturtle127** [comment]
@ClxS Oh, OK. Cool! Can't wait for that as well!
