### ISSUE TITLE
It's spelled Author, not Authour. Please correct.

### ISSUE THREAD

**Issue by AdvizeGH** [ClxS/SMAPI#62]
That is all.

**Comment by vgturtle127** [comment]
@AdvizeGH Authour is the British English spelling, Author is the American English spelling. They are both correct, so either is fine.

**Comment by ClxS** [comment]
I wont be changing it in SMAPI since it will make all prior mods incompatible for a pretty small change. Authour is the (somewhat dated) British spelling.

It's been addressed already in the private branch for the future version though.
