### ISSUE TITLE
Help command

### ISSUE THREAD

**Issue by darkvergus** [ClxS/SMAPI#65]
When typing help in the console it doesn't work like before, in fact it only sends the message "System.Linq.Enumerable+WhereSelectListIterator`2[StardewModdingAPI.Command,System.String]"

**Comment by ClxS** [comment]
Ah thanks for pointing this out!

**Comment by Zoryn4163** [comment]
Fixed in 36fb605a7c5262a04e2752c55ae97093d26c1a73 or sometime after.
Will be fixed in next release build hopefully. Will close then.
