### ISSUE TITLE
Please, add backwards compatibility for "Version"

### ISSUE THREAD

**Issue by speeder** [ClxS/SMAPI#66]
Seemly the way to declare a mod version (using deprecated Mod.Version or the manifest) changed from a string to a struct, this made several mods (like all of mine) to stop working and cause exceptions.

**Comment by Zoryn4163** [comment]
If it's too hard to figure out how to copy/paste from the example you can remove the 'Version' line completely and the next time the manifest is read it will be automatically added.

**Comment by Zoryn4163** [comment]
36a3401e14ce911e1c2a7855d2d4d9a709fbf526
There. Don't bother complaining about this more.
It'll be available to 'use' in the next release build.
