### ISSUE TITLE
Use <modName>.json to load mods

### ISSUE THREAD

**Issue by ClxS** [ClxS/SMAPI#7]
Moving towards doing this sets us up to be able to load file only and content only mods in the future. It'll break existing mods but steps can be taken to make it backwards compatible for a while.

**Comment by vgturtle127** [comment]
@ClxS Isn't this what Storm does?

**Comment by ClxS** [comment]
Yep, but it was originally one of Zoryn's plans on her todo list.

**Comment by vgturtle127** [comment]
@ClxS Does this mean you could eventually load Storm and SMAPI mods at the same time? That would be cool, then nobody would have to choose.

**Comment by ClxS** [comment]
Unfortunately not, Storm relies on features which I feel greatly reduce the power of the API, which is why some ones are plain impossible in Storm atm.

However, a new major update is coming which provide greater power than storm with backwards compatibility with SMAPI.

**Comment by Zoryn4163** [comment]
#33 Does this, except not for content-only mods. When support for that is added, the requirement for EntryDll can be safely removed.

**Comment by vgturtle127** [comment]
@ClxS I suppose I should have guessed there would be incompatibilities, Storm and SMAPI are handled pretty differently.

I am downloading the new SMAPI now. :smile:
