### ISSUE TITLE
[Req] Pre-event: Farmer.changeAccessory()

### ISSUE THREAD

**Issue by ThatNorthernMonkey** [ClxS/SMAPI#73]
For some reason this limits the available accessories to 20, could do with overriding it and returning early if people want to add more accessories.

**Comment by AdvizeGH** [comment]
Jinxiewinxie and I had no problem allowing a player to use more accessories by bypassing this method entirely, unfortunately it is also called when the save file is loaded so it then defaults the player's chosen accessory to < 20. Overriding this method would be nice.

**Comment by ClxS** [comment]
This wont be possible SMAPI, so I'll close this issue. I've opened one over on the Farmhand issue list :)
https://github.com/ClxS/Stardew-Farmhand/issues/34
