### ISSUE TITLE
"filenotfoundexception"

### ISSUE THREAD

**Issue by beethozart** [ClxS/SMAPI#75]
the application says it cannot find main string paths or configure paths. I may have done something wrong but i'm not sure what it would be.

**Comment by Zoryn4163** [comment]
Can you provide a full screenshot of the error or a pastebin of the program log in appdata\stardewvalley\errorlogs?

**Comment by beethozart** [comment]
![capture](https://cloud.githubusercontent.com/assets/18124413/14087259/ffc6b39e-f4f6-11e5-9cf1-93d9673a3ba9.PNG)

**Comment by Zoryn4163** [comment]
That means SMAPI can't find your Stardew exe. It must be in the same folder as SMAPI and it must be called "Stardew Valley.exe" - you may not see .exe if you have extensions turned off

**Comment by beethozart** [comment]
Okay so, I just move my exe to the Smapi folder and it's fixed? I'm still new to windows 10 so I guess I missed that it was hidden.
