### ISSUE TITLE
Launch Failure

### ISSUE THREAD

**Issue by ImmortalMudkip** [ClxS/SMAPI#76]
So, I installed all of the contents and mods that IDEDOnline instructed to in this: https://www.youtube.com/watch?v=dzNdBlPokr4 video and I clicked on the StardewModdingAPI.exe to launch the game, the box that normally appears asking for admin permission to run it came up, I selected "Run", and then the black text box popped up that is supposed to show you which mods are working then launch the game, but instead of showing that which was just listed, it displayed this: https://gyazo.com/00d4dba0cddd1a216ec6befd0537d21f. It stayed like that until I closed the window, and I don't know how to fix it to launch the game correctly.

**Comment by tstaples** [comment]
Which version of SMAPI are you using?

**Comment by ImmortalMudkip** [comment]
39.3 and latest version of Stardew Valley.

**Comment by tstaples** [comment]
I was able to re-create this bug by deleting my errors logs folder ("%AppData%/Roaming/StardewValley/ErrorLogs"). 

A temporary work-around would be to create the "ErrorLogs" folder in that directory.

**Comment by ImmortalMudkip** [comment]
Thanks, it worked. Is it a permanent fix?

**Comment by tstaples** [comment]
No. I'm looking into a proper fix.
