### ISSUE TITLE
new graphics events don't work properly

### ISSUE THREAD

**Issue by speeder** [ClxS/SMAPI#80]
The events:

OnPostRenderGuiEvent and OnPreRenderGuiEvent fire, but doesn't work at all.

If you enable "menu background", they stop firing too.

OnPreRenderHudEvent and OnPostRenderHudEvent also fire, but also doesn't work (you can't use them to actually render anything).

Also performance of 0.93.3 is abysmal, game runs at about 20 FPS on my computer (while on 0.93.2 it runs at 60 most of the time).

Sometimes (for example when those pink birds are flying before the main menu) it stutters too.

**Comment by ClxS** [comment]
I'll have a look at the performance when I get chance. 0.39.3 is still marked as a pre-release so people will only get it from the forum if they did it intentionally.

I suspect the new draw call is to blame.

**Comment by Zoryn4163** [comment]
Well I can say for a fact that calling reflection 12 or so times an update isn't great for performance. I changed it so that it caches the methodinfo so that should help a little. I'm trying to figure out the sillyness with the mines being black when base.Draw() is commented out.

I would honestly advise support stop with SMAPI if that new API is coming out soon, as it seems to completely annihilate the issues SMAPI faces.

**Comment by ThatNorthernMonkey** [comment]
do you have any new info on the new API? Someone mentioned in chat that dev on the other API has stopped, i haven't been able to get a response from KL as to whether its true or not though but certainly nothing has been said by him on the subject for a long while. It may just be SMAPI all the way.

**Comment by Zoryn4163** [comment]
@ClxS Has been doing some amazing work on a new API, hang tight :smile:

**Comment by ThatNorthernMonkey** [comment]
Oh i thought you were referring to that other mysterious API, not the one CLxS has been working on. That's good then :)

**Comment by Zoryn4163** [comment]
The only other API I knew of was the one that Zendarva was working on, but I haven't heard anything on that in a while. Anyways I'm off to work. If I don't pass out when I get home today I'll look more into the graphics events.

**Comment by speeder** [comment]
If https://github.com/ClxS/SMAPI/pull/85 is merged, I believe we can close this. (at least from the testing I've done here with mine and CJBok mods)

**Comment by speeder** [comment]
This is indeed, fixed, but another old issue ins't.
