### ISSUE TITLE
Missing Method?

### ISSUE THREAD

**Issue by Reggie4u2** [ClxS/SMAPI#88]
Whenever I try to run my game it trows a System.MissingMethodException

**Comment by Zoryn4163** [comment]
Details?

**Comment by Reggie4u2** [comment]
I recently installed the cheats menu mod and after placing everything in its respected folder I click in SMAPI.exe and when the command prompt comes up it says a bunch of things then says "Game failed to start: System.MissingMethodException: Method not found: 'Int32 StardewValley.Game1.getMouseX()'.
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at StardewModdingAPI.Program.RunGame()"

**Comment by Zoryn4163** [comment]
Does this occur with no mods installed? Which version of SMAPI are you using?

**Comment by Reggie4u2** [comment]
Yes it happens without any mods installed and I'm using 0.39.4

**Comment by Zoryn4163** [comment]
Have you tried 0.39.5?

**Comment by Reggie4u2** [comment]
Yes I have

**Comment by Zoryn4163** [comment]
I'm 99% certain that a mod is causing that. Are you certain your mods folder is **empty**?

**Comment by Reggie4u2** [comment]
Yes the mod folder is completely empty

**Comment by Zoryn4163** [comment]
Try deleting the entire mods folder itself. I cannot reproduce this, and I've yet to have anyone that's tested my builds run into this.

**Comment by Reggie4u2** [comment]
I am so sorry I figured out what was causing the problem it was purely due to my own negligence that this happened. I forgot I copied my steam folders and I was running everything from the wrong folder. Everything is working perfectly now I am sorry for causing you trouble.

**Comment by Zoryn4163** [comment]
It's all good. Have a nice day/evening.
