### ISSUE TITLE
Missing Method Exceptions

### ISSUE THREAD

**Issue by Amedee12** [ClxS/SMAPI#90]
I've been trying to get to play Stardew Valley with this mod, but it's not working. I've done everything to set it up correctly, but it's still not working.

Method not found 'System.Threading.Tasks.Task System.Treading.Tasks.Task.Run<System.Action>'

I really want to use this mod.

Please help if you can. Thank you.

**Comment by tstaples** [comment]
Are you having an issue with a particular mod, or SMAPI itself? If the former, which mod and are you able to run SMAPI without that mod? If the latter, which version of SMAPI are you using?

**Comment by Amedee12** [comment]
Honestly, I'm not too sure.. Because I haven't been able to get into the game at all while clicking on the mod, so.. I'm not sure which is wrong. I've tried like every combination.

**Comment by CJBok** [comment]
@Amedee12 make sure you have done the following.
- Have .NET Framework 4.5 installed.
- Have Stardew Valley 1.06 installed.
- Have SMAPI 0.39.6 installed.
- Have StardewModdingAPI.exe installed next to Stardew Valley.exe.
- Run StardewModdingAPI.exe.
