### ISSUE TITLE
SMAPI Minigame Crash

### ISSUE THREAD

**Issue by Ellipticalinaly** [ClxS/SMAPI#95]
Latest release of Smapi .39.

Game crashes on any and all minigames, the Prairie King with Abigail, Fishing Mini Game at Festival, Shooting Gallery minigame, all Casino games, the arcade games.

SMAPI is the core of the issue, tried to see which mod it was by checking every mod one at a time, then no mods, SMAPI still crashes on minigames.

**Comment by ClxS** [comment]
Uhoh, thought this would've been fixed!
Thanks for the report, we'll have a look into it! :)

**Comment by Ellipticalinaly** [comment]
<3 thanks for trying your best on smapi, we all appreciate the work you guys do. You do you bby.

**Comment by ClxS** [comment]
Hey @Ellipticalinaly, would you be able to attach the SMAPI error log? It's in %AppData%\StardewValley\ErrorLogs

**Comment by speeder** [comment]
I am puzzled by this bug... I tested it, and saw no problems! But I can't get in the Cassino yet, thus this might be the reason too...

**Comment by Ellipticalinaly** [comment]
The error log doesn't seem to show anything, just the regular stuff after loading up on the cmd

[
[11:34:35.522 AM] Validating api paths...
[11:34:36.530 AM] Initializing SDV Assembly...
[11:34:36.607 AM] Starting SDV...
[11:34:36.612 AM] Injecting New SDV Version...
[11:34:38.116 AM] Patching SDV Graphics Profile...
[11:34:38.144 AM] LOADING MODS
[11:34:38.148 AM] LOADED 0 MODS
[11:34:38.149 AM] Initializing Console Input Thread...
[11:34:38.148 AM] SDV Loaded Into Memory
[11:34:38.166 AM] Registered command: help
[11:34:38.172 AM] Applying Final SDV Tweaks...
[11:34:38.789 AM] XNA Initialize
[11:34:38.828 AM] XNA LoadContent
[11:34:41.847 AM] Initializing Debug Assets...
[11:34:49.744 AM] Game Loaded
[11:34:49.745 AM] Type 'help' for help, or 'help <cmd>' for a command's usage
]

**Comment by Parthenos** [comment]
[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/ClxS/SMAPI/files/201001/MODDED_ProgramLog.Log_LATEST.txt)

Sorry for the german error messages.

**Comment by ClxS** [comment]
Hi @Ellipticalinaly :), looking at the log it doesn't look like you have the very latest release (0.39.6), it only released a few hours after you had this issue so you probably didn't see it
The issue with the casino breaking was one big issue that existed in the 0.39.4 and .5 versions, but is hopefully fixed now.

Give it a go using the latest version here and let me know if it still doesn't work :)
https://github.com/ClxS/SMAPI/releases/tag/0.39.6

**Comment by CJBok** [comment]
Hi @Parthenos seems like you are using the beta version of Stardew Valley. SMAPI hasn't been created / tested yet for beta versions.

**Comment by CJBok** [comment]
Solved #93

**Comment by Ellipticalinaly** [comment]
Thanks you guys, works good.
